import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from "react";
import NavbarFragment from "./fragments/NavbarFragment"
import PageFragment from "./fragments/PageFragment"
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-gray-50 light">
      <body className="h-full ">
        <Suspense>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="row app-module-content">
              <div className="col col-md-2">
              <NavbarFragment user={''} />
              </div>
              <div className="col col-md-10">
                  <div className="app-module-view">
                  <PageFragment>{children}</PageFragment>
                  </div>
              </div>
          </div>
          </main>
        </Suspense>
      </body>
    </html>

  )
}
